version: '3.8'
services:
  web:
    build: .
    ports:
      - "9082:9082"
    volumes:
      - ./:/app
    environment:
      - PORT=9082
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
